name: Lint

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - 'doc/**'
      - 'markdown/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - 'doc/**'
      - 'markdown/**'

permissions:
  contents: read

concurrency:
  group: lint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Download modules
        run: go mod download

      - name: Run go fmt/vet (Make)
        run: make fmtvet

      - name: Run golangci-lint (Action)
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=5m
